apiVersion: v1
data:
  connect-mirror-maker.properties: |
    # Clusters
    clusters = strimzi, redpanda

    strimzi.bootstrap.servers = aiot-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
    redpanda.bootstrap.servers = redpanda-headless.aiot.svc.cluster.local:9092

    # Replication strimzi -> redpanda
    strimzi->redpanda.enabled = true
    strimzi->redpanda.topics = telemetry

    # Disable reverse
    redpanda->strimzi.enabled = false

    # Replication config
    replication.factor = 3

    # Remove source prefix (telemetry, not strimzi.telemetry)
    replication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy

    # Consumer config
    strimzi->redpanda.consumer.auto.offset.reset = earliest

    # Sync config
    sync.topic.configs.enabled = true
    sync.topic.acls.enabled = false
    refresh.topics.interval.seconds = 30
    emit.heartbeats.enabled = true
    emit.checkpoints.enabled = true

    # Performance
    tasks.max = 2
    offset.flush.interval.ms = 10000
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"connect-mirror-maker.properties":"# Clusters\nclusters = strimzi, redpanda\n\nstrimzi.bootstrap.servers = aiot-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092\nredpanda.bootstrap.servers = redpanda-headless.aiot.svc.cluster.local:9092\n\n# Replication strimzi -\u003e redpanda\nstrimzi-\u003eredpanda.enabled = true\nstrimzi-\u003eredpanda.topics = telemetry\n\n# Disable reverse\nredpanda-\u003estrimzi.enabled = false\n\n# Replication config\nreplication.factor = 3\n\n# Remove source prefix (telemetry, not strimzi.telemetry)\nreplication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy\n\n# Consumer config\nstrimzi-\u003eredpanda.consumer.auto.offset.reset = earliest\n\n# Sync config\nsync.topic.configs.enabled = true\nsync.topic.acls.enabled = false\nrefresh.topics.interval.seconds = 30\nemit.heartbeats.enabled = true\nemit.checkpoints.enabled = true\n\n# Performance\ntasks.max = 2\noffset.flush.interval.ms = 10000\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"mm2-config","namespace":"aiot"}}
  creationTimestamp: "2026-03-05T18:42:20Z"
  name: mm2-config
  namespace: aiot
  resourceVersion: "804543"
  uid: eb0eee9a-4039-4794-af9d-62351835e56e
