apiVersion: v1
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "AIoT PostgreSQL",
          "Group": "Servers",
          "Host": "10.98.61.21",
          "Port": 5432,
          "MaintenanceDB": "aiot",
          "Username": "aiot_admin",
          "SSLMode": "prefer"
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"servers.json":"{\n  \"Servers\": {\n    \"1\": {\n      \"Name\": \"AIoT PostgreSQL\",\n      \"Group\": \"Servers\",\n      \"Host\": \"10.98.61.21\",\n      \"Port\": 5432,\n      \"MaintenanceDB\": \"aiot\",\n      \"Username\": \"aiot_admin\",\n      \"SSLMode\": \"prefer\"\n    }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"pgadmin-servers","namespace":"aiot"}}
  creationTimestamp: "2026-03-05T16:23:58Z"
  name: pgadmin-servers
  namespace: aiot
  resourceVersion: "785414"
  uid: b0bbfa2c-2a38-4dcb-a10a-8e0cdb8c6d5d
