apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-indexer
  namespace: aiot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qdrant-indexer
  template:
    metadata:
      labels:
        app: qdrant-indexer
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: qdrant-indexer
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - pip install kafka-python qdrant-client lz4 --quiet && python /code/indexer.py
        command:
        - /bin/sh
        - -c
        image: python:3.11-slim
        name: qdrant-indexer
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - mountPath: /code
          name: code
      volumes:
      - configMap:
          name: qdrant-indexer-code
        name: code
