apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-pg-flusher
  name: redis-pg-flusher
  namespace: aiot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-pg-flusher
  template:
    metadata:
      labels:
        app: redis-pg-flusher
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: redis-pg-flusher
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - pip install --quiet redis psycopg2-binary && python3 /code/flusher.py
        command:
        - /bin/sh
        - -c
        image: python:3.11-slim
        name: flusher
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /code
          name: code
      volumes:
      - configMap:
          name: redis-pg-flusher-code
        name: code
