apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pg-sink
  name: pg-sink
  namespace: aiot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pg-sink
  template:
    metadata:
      labels:
        app: pg-sink
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: pg-sink
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - pip install kafka-python-ng psycopg2-binary lz4 --quiet && python3 /code/pg_sink.py
        command:
        - /bin/sh
        - -c
        image: python:3.11-slim
        name: pg-sink
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /code
          name: code
      volumes:
      - configMap:
          name: pg-sink-code
        name: code
