apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-twin
  namespace: aiot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digital-twin
  template:
    metadata:
      labels:
        app: digital-twin
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: digital-twin
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - python3
        - /code/twin.py
        env:
        - name: PYTHONPATH
          value: /shared
        image: python:3.11-slim
        name: digital-twin
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: 1500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        volumeMounts:
        - mountPath: /code
          name: code
        - mountPath: /shared
          name: packages
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z redis-master.aiot.svc.cluster.local 6379; do sleep 2; done
        image: busybox
        name: wait-for-redis
      - command:
        - sh
        - -c
        - until nc -z redpanda.aiot.svc.cluster.local 9092; do sleep 2; done
        image: busybox
        name: wait-for-redpanda
      - command:
        - sh
        - -c
        - pip install kafka-python redis flask lz4 && cp -r /usr/local/lib/python3.11/site-packages/* /shared/
        image: python:3.11-slim
        name: pip-install
        volumeMounts:
        - mountPath: /shared
          name: packages
      volumes:
      - configMap:
          name: digital-twin-code-v3
        name: code
      - emptyDir: {}
        name: packages
